# Logo Url
# Please enter an absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: 
    url: /css/images/keralajs_log.png
    width: 100px
    height: 100px

# Header
menu:
  Home: /
  # Delete this row if you don't want categories in your header nav bar
  Categories:
  Forum: https://groups.google.com/forum/#!forum/kerala-js
  About: /about/index.html

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: true

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left # sidebar's position (left or right)
social_links:
  twitter: https://twitter.com/KeralaJS
  facebook: https://www.facebook.com/groups/167550890111124/
  google-plus: https://plus.google.com/communities/111701013157558770020
  github: https://github.com/KeralaJS
  weibo:
  rss:

widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  Facebook: https://www.facebook.com/groups/167550890111124/
  Twitter: https://twitter.com/KeralaJS

# Don't Use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
fb_admins:
fb_app_id:
